[package]
name = "keeper-crabby"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.0"
sha2 = "0.10.8"
directories = "5.0.1"
aes-gcm-siv = "0.11.1"
dyn-clone = "1.0.17"
scrypt = "0.11.0"
rand = "0.8.4"
dotenv = "0.15.0"
downcast-rs = "1.2.1"
