name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  KRAB_TEMP_DIR: /tmp/krab

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create temp directory
      run: mkdir -p $KRAB_TEMP_DIR
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
